@startuml
left to right direction
skinparam linetype polyline
package "Frontend" {
    [App] --> [Title]
    [App] --> [MessageDisplay] : "Zeigt Meldungen"
    [App] --> [InputField] : "Abfahrtsort"
    [App] --> [InputField] : "Zielort"
    [App] --> [DatumPicker] : "Abfahrtszeit"
    [App] --> [Button] : "Absenden"
    [App] --> [ComparisonTable] : "Zeigt Reisemöglichkeiten"
}

package "Utils" {
    component "EventBus" {
    queue "Success Queue" as SuccessQueue
    queue "Error Queue" as ErrorQueue
}


    [App] --> SuccessQueue : "Publiziert Success"
    [formValidationHandler] --> ErrorQueue : "Publiziert Error"

    [MessageDisplay] <-- SuccessQueue : "Konsumiert Success"
    [MessageDisplay] <-- ErrorQueue : "Konsumiert Error"
}

package "API" {
    [google-maps-routes-api]
    [App] <--> [google-maps-routes-api] : "Holt Reisedaten"
}
@enduml
