@startuml ComponentDiagram
skinparam linetype polyline
package "Frontend" {
    [App] --> [Title]
    [App] --> [MessageDisplay]
    [App] --> [Formular]
    [App] --> [Comparison]
}

component "Formular" {
    [InputField Abfahrtsort]
    [Datepicker]
    [InputField Zielort]
    [Button Absenden]
}

component "Comparison" {
    [ComparisonTable]
    [Diagram Duration]
    [Diagram Distance]
}

package "Utils" {
    component "EventBus" {
    queue "Success Queue" as SuccessQueue
    queue "Error Queue" as ErrorQueue
    queue "Travel Data" as TravelData
    queue "Diagram Data" as DiagramData
}


    [App] --> SuccessQueue : "Publiziert Success"
    [formValidationHandler] --> ErrorQueue : "Publiziert Error"

    [MessageDisplay] <-- SuccessQueue : "Konsumiert Success"
    [MessageDisplay] <-- ErrorQueue : "Konsumiert Error"
}

package "API" {
    [googleMapsAPI]
    [Formular] --> [googleMapsAPI] : "Bestellt Reisedaten"
    [googleMapsAPI] --> [TravelData] : "Publiziert Travel Data"
    [googleMapsAPI] --> [DiagramData] : "Publiziert Diagram Data"
}

[TravelData] --> [Comparison] : "konsumiert Travel Data"
[DiagramData] --> [Comparison] : "konsumiert Diagram Data"

@enduml
